name: shopmy
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0




dependencies:
  flutter:
    sdk: flutter


  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.2.0
  lottie: ^2.7.0
  shimmer: ^3.0.0
  connectivity_plus: ^5.0.1
  url_launcher: ^6.2.6
  flutter_native_splash: any
  smooth_page_indicator: ^1.1.0




  iconsax_flutter: ^1.0.0
  cupertino_icons: ^1.0.8


  get: ^4.6.6
  get_storage: ^2.1.1

  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2


  firebase_core: ^3.13.1
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  google_sign_in: ^6.3.0
  image_picker: ^1.1.2
  firebase_storage: ^12.4.6
  cached_network_image: ^3.4.1

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#272727"
  image: assets/logos/logo_black.png
  image_dark: assets/logos/logo_white.png
  android_gravity: fill


  android_12:
    color: "#FFFFFF"
    color_dark: "#272727"
    image: assets/logos/logo_black.png
    image_dark: assets/logos/logo_white.png
    android_gravity: fill/center



  web: false





  #--------------- ./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2


flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/on_boarding_images/
    - assets/images/signUpImages/
    - assets/images/success_email/
    - assets/images/loaders/
    - assets/images/categories/
    - assets/images/products/jackets/
    - assets/images/user/
    - assets/icons/payment/
    - assets/images/products/tshirts/



  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800