// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcYOrf94iU2bQjnry7PtQG3DmFFPY8qHk',
    appId: '1:768487417984:web:be0c059ccded1be022de65',
    messagingSenderId: '768487417984',
    projectId: 'shopmy-df84a',
    authDomain: 'shopmy-df84a.firebaseapp.com',
    storageBucket: 'shopmy-df84a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu4BxnItvd3y84r2OhFpSGH6XYVs8zW3Y',
    appId: '1:768487417984:android:36ec18647519aa9922de65',
    messagingSenderId: '768487417984',
    projectId: 'shopmy-df84a',
    storageBucket: 'shopmy-df84a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTsOCGX8xSM9_MAaVBNTZBoqb8z8QQBaQ',
    appId: '1:768487417984:ios:d41539166575b1dc22de65',
    messagingSenderId: '768487417984',
    projectId: 'shopmy-df84a',
    storageBucket: 'shopmy-df84a.firebasestorage.app',
    androidClientId:
        '768487417984-5fghm6cgbodc3ae5pvn727ce4cb7rhhj.apps.googleusercontent.com',
    iosClientId:
        '768487417984-imu7ngvbvtcg9arru9qkn61cer2aqk6b.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopmy',
  );
}
